### ISSUE TITLE
Drop Original Feature when Encoding 

### ISSUE THREAD

**Issue by pGit1** [wdm0006/categorical_encoding#4]
Can we set an option to drop the original feature feat_0 for the numeric encoders?

See this code below:

import category_encoders
import pandas as pd
import numpy as np

dd = {'feat1':['a','b','c','d','e'],'feat2':np.random.random(size=(5))}
df = pd.DataFrame(dd)
encoder = category_encoders.BackwardDifferenceEncoder(cols=['feat1'])
encoder.fit_transform(df)

this returns feat_0 as the first feaure and every row element is the number 1. Is this a desired property of should it be removed?

**Comment by wdm0006** [comment]
Thats a good idea.  I use the [Statsmodels Contrasts](http://statsmodels.sourceforge.net/devel/contrasts.html) functionality as closely as possible, and using your snippet modified to use different numbers of categories (up to 1000), it does seem that feat_0 has no obvious use.

I think rather than adding an option specific to this particular case (index 0 feature after backwards difference), adding an option to all encoders called something like 'drop_invariant', that dropped any columns with variance of 0 (or perhaps below some configurable threshold) would be more useful.

Do you think that would make sense?  If you're interested in helping with that let me know, or I can work on it.

**Comment by pGit1** [comment]
Thanks for the prompt response Will! First ,I think the "drop invariant" idea you propose would be ideal actually. Since I last messaged you I came with this work around code, so not having the option right now is not hurting. See my example adding to my code from the earlier post:

dd = {'feat1':['a','b','c','d','e'],'feat2':np.random.random(size=(5))}
df = pd.DataFrame(dd)
encoder = category_encoders.BackwardDifferenceEncoder(cols=['feat1'])
new_df = encoder.fit_transform(df)

#Delete Feats with Bad behavior for certain encoders
for col in df.columns:
    q = '%s_0'%(col)
    if q in new_df.columns:
        del new_df[q]

It appears that Helmert, Sum, and Polynomial have the same issue but this is easily remedied with the simple for loop below so this technically is not an "issue."

I also looked at your code and I am nowhere near the programmer you are. I would probably get in your way more than I could help with the invariant feature you talked about but if you really wanted me to I could take a stab at something...not sure if it would scale or fit your programming style though! :D

**Comment by wdm0006** [comment]
I'd be happy to help you out along the way, we can do it in a simple way.  

In the transform methods of all of these encoders, we make sure that the X variable is always a dataframe, so you can use pandas tools before returning anything to drop low variance cols:

    df = df.loc[:, df.var()>some_threshold]

So if you just add a parameter to the class for something like 'drop_invariant' as true or false and then 'variance_threshold' as some float, but defaulting to 0.0, then it should be a pretty straight forward addition.  

Try it out and send a pull request, we can get it working.

**Comment by pGit1** [comment]
This: 

> df = df.loc[:, df.var()>some_threshold]
actually makes A LOT of sense. 

What I am scratching my head on is A) How to add the parameter to the Class (or any class for that matter--Classes confuse the crap out of me) and B) How this whole "pull request" thing actually works even if I were able to add the parameter.

Im such a newbie. I'll do my best though and try and send the pull request as soon as I can!

**Comment by wdm0006** [comment]
Github's docs on pull requests are pretty good: https://help.github.com/articles/using-pull-requests/, if you have trouble just let me know. 

As for parameters, look at cols/self.cols in BackwardDifferenceEncoder, that is an example of one.  So you can add another one called 'drop_invariant' defaulting to false in line 49, set it to be an instance variable (i.e. self.x) in line 58ish, then use it as self.drop_invariant in the transform method.

**Comment by wdm0006** [comment]
Here is a pretty good overview on classes and OOP in general in python: https://jeffknupp.com/blog/2014/06/18/improve-your-python-python-classes-and-object-oriented-programming/

**Comment by pGit1** [comment]
Thanks for the resources Will. I'll definitely give it a go as soon as I can!

**Comment by pGit1** [comment]
As a side, for BackDiff,Sum,Polynomial, and Helmert encoder should the dependent variable (y) be specified in the `.fit()` call since the docs state the comparisons are made based on the dependent variable at different levels of the categorical?

So something like this `new_df =BackDifferenceEncoder(cols=['feat1']).fit_transform(df,y) `. What is interesting is that even if the code above is run without specifying y, a new dataframe with different dimensionality is created. I wonder what is going on internally here.

**Comment by wdm0006** [comment]
My understanding is that the regression of the dependent variable against the encoded matrix is the comparison of the dependent against the different levels of the categorical.  So to match the context of the statsmodels docs, we would be using the category encoders in this library as preprocessing before running an OLS regression or something like that on the now-encoded X and y. 

So they'll use:

    ols("write ~ C(race, Helmert)", data=hsb2)


Where we are just doing the C(race, Helmert) part here.

**Comment by pGit1** [comment]
Ah, ok makes perfect sense. Thanks for all your help!

**Comment by wdm0006** [comment]
@pGit1 just checking in, are you still planning to work on this?
