### ISSUE TITLE
Transformers always return pandas dataframes

### ISSUE THREAD

**Issue by wdm0006** [wdm0006/categorical_encoding#5]
All of the transformers in this library use pandas dataframes internally, but will accept either numpy arrays or pandas dataframes as inputs.  They all return dataframes though.  For use in pipelines it may be helpful to optionally return a numpy array (df.values) instead of a dataframe.

If anyone would like to get into contributing, this would be a good starter issue, comment here if you're interested.

**Comment by barnettjacob** [comment]
I'd love to get involved! Is this a case of offering an argument for each method and returning a df or array depending on the option selected?

**Comment by wdm0006** [comment]
You got it! I think it makes sense to default to data frame if nothing is passed but am open to any reasons to do the opposite.

**Comment by barnettjacob** [comment]
Ok, I'll have a look at it later create a PR.

**Comment by wdm0006** [comment]
Awesome, thank you for the help.

**Comment by barnettjacob** [comment]
Will, apologies! I just haven't had time to look at this and I'm going to be away for the next 10 days. I'll be happy to pick it up on my return if it hasn't been tackled.
Jacob

**Comment by wdm0006** [comment]
No rush, if someone else wants to work on this in the meantime then there will be plenty of other ways to help out in a couple of weeks, and if not, then it'll be here for you when you're back.

Safe travels.

**Comment by barnettjacob** [comment]
Thanks Will!

**Comment by wdm0006** [comment]
@barnettjacob just checking in, are you still planning to work on this?

**Comment by barnettjacob** [comment]
Hi Will, apologies for the radio silence. Yes, I am hoping to spend some time on this in the next week.
Cheers, 
Jacob

**Comment by barnettjacob** [comment]
Hi Will, just a quick note to apologise that I haven't been able to find the time to look at this - I've got a lot on and realistically I'm going to struggle to work on it in the near future. Sorry!

I'll circle back when things are a bit quieter and see what I can pick up.
Cheers
Jacob

**Comment by wdm0006** [comment]
Jacob, I totally get that, glad you've found some usefulness in the library, if you do get to a point where you'd like to contribute some code, you know where to find us.
